[workspace]
members = [
    "atlas-cli",
    "atlas-core",
    "atlas-server",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.55"
clap = "4.4.0"
indexmap = "2.6.0"
noodles = "0.87.0"
thiserror = "2.0.3"
tracing = "0.1.30"
tracing-subscriber = "0.3.8"
