[workspace]
members = [
    "atlas-cli",
    "atlas-core",
    "atlas-server",
]
resolver = "2"

[workspace.package]
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.55"
clap = "4.4.0"
thiserror = "1.0.40"
tracing = "0.1.30"
