[package]
name = "atlas"
version = "0.1.0"
authors = ["Michael Macias <michael.macias@stjude.org>"]
edition = "2021"
rust-version = "1.56.0"

[dependencies]
anyhow = "1.0.55"
axum = "0.5.1"
clap = { version = "3.1.1", features = ["derive", "env"] }
dotenv = "0.15.0"
futures = { version = "0.3.21", default-features = false, features = ["std"] }
serde = { version = "1.0.136", features = ["derive"] }
sqlx = { version = "0.5.10", features = ["runtime-tokio-native-tls", "postgres", "time"] }
time = "0.2.27"
tokio = { version = "1.17.0", features = ["macros", "rt-multi-thread"] }
tower = "0.4.12"
tower-http = { version = "0.2.3", features = ["add-extension", "trace", "util"] }
tracing = "0.1.30"
tracing-subscriber = "0.3.8"

[dev-dependencies]
hyper = "0.14.17"
rand = "0.8.5"
serde_json = "1.0.79"
