services:
  devcontainer:
    build: .
    volumes:
      - ..:/workspaces/atlas:cached
      - target:/workspaces/atlas/target:cached
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgres:15.3
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "dev"

volumes:
  db:
  target:
