[package]
name = "atlas-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
ndarray = "0.16.1"
noodles = { version = "0.83.0", features = ["core", "gff"] }
thiserror.workspace = true
tracing.workspace = true
