[package]
name = "atlas-core"
version = "0.1.0"
edition.workspace = true

[dependencies]
indexmap.workspace = true
ndarray = "0.16.1"
noodles = { workspace = true, features = ["core", "gff"] }
thiserror.workspace = true
tracing.workspace = true
